static const char *NpHvkMaterialNames[] =
{
	"Stone",
	"Cloth",
	"Dirt",
	"Glass",
	"Grass",
	"Metal",
	"Organic",
	"Skin",
	"Water",
	"Wood",
	"Heavy Stone",
	"Heavy Metal",
	"Heavy Wood",
	"Chain",
	"Snow",
	"Stone Stairs",
	"Cloth Stairs",
	"Dirt Stairs",
	"Glass Stairs",
	"Grass Stairs",
	"Metal Stairs",
	"Organic Stairs",
	"Skin Stairs",
	"Water Stairs",
	"Wood Stairs",
	"Heavy Stone Stairs",
	"Heavy Metal Stairs",
	"Heavy Wood Stairs",
	"Chain Stairs",
	"Snow Stairs",
	"Elevator",
	"SKY_MAT_LIGHT_WOOD", 
	"SKY_MAT_BROKEN_STONE",
	"SKY_MAT_SNOW",
	"SKY_MAT_GRAVEL",
	"SKY_MAT_MATERIAL_CHAIN_METAL",
	"SKY_MAT_WOOD",
	"SKY_MAT_SKIN",
	"SKY_MAT_BARREL",
	"SKY_MAT_MATERIAL_CERAMIC_MEDIUM",
	"SKY_MAT_MATERIAL_BASKET",
	"SKY_MAT_ICE",
	"SKY_MAT_STAIRS_STONE",
	"SKY_MAT_MATERIAL_BLADE_1HAND",
	"SKY_MAT_WATER",
	"SKY_MAT_UNKNOWN_1028101969",
	"SKY_MAT_MATERIAL_BOOK", 
	"SKY_MAT_SOLID_METAL",
	"SKY_MAT_MATERIAL_AXE_1HAND",
	"SKY_MAT_UNKNOWN_1440721808",
	"SKY_MAT_STAIRS_WOOD",
	"SKY_MAT_MUD",
	"SKY_MAT_STAIRS_SNOW",
	"SKY_MAT_UNKNOWN_",
	"SKY_MAT_UNKNOWN_",
	"SKY_MAT_MATERIAL_BOWS_STAVES",
	"SKY_MAT_MATERIAL_WOOD_AS_STAIRS",
	"SKY_MAT_GRASS",
	"SKY_MAT_MATERIAL_BOULDER_LARGE",
	"SKY_MAT_MATERIAL_STONE_AS_STAIRS",
	"SKY_MAT_MATERIAL_BLADE_2HAND",
	"SKY_MAT_MATERIAL_BOTTLE_SMALL",
	"SKY_MAT_SAND",
	"SKY_MAT_HEAVY_METAL",
	"SKY_MAT_DRAGON",
	"SKY_MAT_MATERIAL_BLADE_1HAND_SMALL",
	"SKY_MAT_MATERIAL_SKIN_SMALL",
	"SKY_MAT_STAIRS_BROKEN_STONE",
	"SKY_MAT_MATERIAL_SKIN_LARGE",
	"SKY_MAT_ORGANIC",
	"SKY_MAT_MATERIAL_BONE",
	"SKY_MAT_HEAVY_WOOD",
	"SKY_MAT_MATERIAL_CHAIN",
	"SKY_MAT_DIRT",
	"SKY_MAT_MATERIAL_ARMOR_LIGHT",
	"SKY_MAT_MATERIAL_SHIELD_LIGHT",
	"SKY_MAT_MATERIAL_COIN",
	"SKY_MAT_MATERIAL_SHIELD_HEAVY",
	"SKY_MAT_MATERIAL_ARMOR_HEAVY",
	"SKY_MAT_MATERIAL_ARROW",
	"SKY_MAT_GLASS",
	"SKY_MAT_STONE",
	"SKY_MAT_CLOTH",
	"SKY_MAT_MATERIAL_BLUNT_2HAND",
	"SKY_MAT_MATERIAL_BOULDER_MEDIUM",
	NULL
};

static const char *NpHvkLayerNames[] =
{
	"Unidentified",
	"Static",
	"AnimStatic",
	"Transparent",
	"Clutter",
	"Weapon",
	"Projectile",
	"Spell",
	"Biped",
	"Tree",
	"Prop",
	"Water",
	"Trigger",
	"Terrain",
	"Trap",
	"NonCollidable",
	"CloudTrap",
	"Ground",
	"Portal",
	"Stairs",
	"CharController",
	"AvoidBox",
	"?",
	"?",
	"CameraPick",
	"ItemPick",
	"LineOfSight",
	"PathPick",
	"CustomPick1",
	"CustomPick2",
	"SpellExplosion",
	"DroppingPick",
	"Other",
	"Head",
	"Body",
	"Spine1",
	"Spine2",
	"LUpperArm",
	"LForeArm",
	"LHand",
	"LThigh",
	"LCalf",
	"LFoot",
	"RUpperArm",
	"RForeArm",
	"RHand",
	"RThigh",
	"RCalf",
	"RFoot",
	"Tail",
	"SideWeapon",
	"Shield",
	"Quiver",
	"BackWeapon",
	"BackWeapon",
	"PonyTail",
	"Wing",
	NULL
};

static const char *NpHvkMotionSystems[] =
{
	"0: Invalid",
	"1: Dynamic",
	"2: Sphere",
	"3: Sphere Inertia",
	"4: Box",
	"5: Box Stabilized",
	"6: Keyframed",
	"7: Fixed",
	"8: Thin Box",
	"9: Character",
	NULL
};

static const char *NpHvkQualityTypes[] =
{
	"0: Invalid",
	"1: Fixed",
	"2: Keyframed",
	"3: Debris",
	"4: Moving"
	"5: Critical",
	"6: Bullet",
	"7: User",
	"8: Character",
	"9: Keyframed Report",
	NULL
};
